const indianStates = [
  {
    state: "Andhra Pradesh",
    location: [
      "Tirupati",
      "Visakhapatnam",
      "Amaravati",
      "Kurnool",
      "Rajahmundry",
      "Chittoor",
      "Ponduru",
      "Srikalahasti",
      "Eluru",
      "Araku Valley",
      "Anantapur",
      "Nellore",
      "Machilipatnam",
      "Kakinada",
      "Pondicherry",
    ],
  },
  {
    state: "Arunachal Pradesh",
    location: [
      "Tawang",
      "Itanagar",
      "Ziro Valley",
      "Bomdila",
      "Namdapha National Park",
      "Sela Pass",
      "Mechuka",
      "Pasighat",
      "Monigong",
      "Roing",
      "Tezu",
      "Dirang",
      "Anini",
      "Kalaktang",
      "Kameng Wildlife Sanctuary",
    ],
  },
  {
    state: "Assam",
    location: [
      "Guwahati",
      "Kaziranga National Park",
      "Jorhat",
      "Tezpur",
      "Majuli",
      "Sivasagar",
      "Nameri National Park",
      "Bihu Festival",
      "Haflong",
      "Dibrugarh",
      "Tinsukia",
      "Barpeta",
      "Manas National Park",
      "Kamakhya Temple",
      "Diphu",
    ],
  },
  {
    state: "Bihar",
    location: [
      "Patna",
      "Bodh Gaya",
      "Nalanda",
      "Rajgir",
      "Vaishali",
      "Munger",
      "Sonepur",
      "Bhagalpur",
      "Gaya",
      "Kushinagar",
      "Purnea",
      "Jahanabad",
      "Darbhanga",
      "Sasaram",
      "Patliputra",
    ],
  },
  {
    state: "Chhattisgarh",
    location: [
      "Raipur",
      "Bilaspur",
      "Chitrakote Falls",
      "Kanger Valley National Park",
      "Sirpur",
      "Dongargarh",
      "Raigarh",
      "Tirathgarh Waterfalls",
      "Bastar",
      "Maitri Bagh",
      "Dhamtari",
      "Rajnandgaon",
      "Kailash and Kanger Caves",
      "Pawapuri",
      "Khutaghat Dam",
    ],
  },
  {
    state: "Goa",
    location: [
      "North Goa",
      "South Goa",
      "Panaji",
      "Calangute Beach",
      "Baga Beach",
      "Anjuna Beach",
      "Vasco da Gama",
      "Candolim Beach",
      "Palolem Beach",
      "Dona Paula",
      "Old Goa",
      "Basilica of Bom Jesus",
      "Se Cathedral",
      "Chapora Fort",
      "Miramar Beach",
    ],
  },
  {
    state: "Gujarat",
    location: [
      "Ahmedabad",
      "Surat",
      "Vadodara",
      "Rann of Kutch",
      "Gir National Park",
      "Dwarka",
      "Somnath",
      "Statue of Unity",
      "Kutch",
      "Sasan Gir",
      "Junagadh",
      "Mount Abu",
      "Lothal",
      "Diu",
      "Palitana",
    ],
  },
  {
    state: "Haryana",
    location: [
      "Chandigarh",
      "Gurugram (Gurgaon)",
      "Kurukshetra",
      "Ambala",
      "Panchkula",
      "Sultanpur National Park",
      "Pinjore Gardens",
      "Baba Farid's Tomb",
      "Morni Hills",
      "Karnal",
      "Faridabad",
      "Rewari",
      "Tughlakabad Fort",
      "Sohna",
      "Manesar",
    ],
  },
  {
    state: "Himachal Pradesh",
    location: [
      "Shimla",
      "Manali",
      "Kullu",
      "Dharamshala",
      "Kangra",
      "Kasauli",
      "Dalhousie",
      "Spiti Valley",
      "Chamba",
      "Nainital",
      "Tirthan Valley",
      "Solang Valley",
      "Rohtang Pass",
      "Bir Billing",
      "Mcleodganj",
    ],
  },
  {
    state: "Jharkhand",
    location: [
      "Ranchi",
      "Jamshedpur",
      "Dhanbad",
      "Deoghar",
      "Hazaribagh",
      "Netarhat",
      "Jharia",
      "Chotanagpur Plateau",
      "Betla National Park",
      "Rajrappa Waterfall",
      "Trikut Parvat",
      "Sundernagar",
      "Dassam Falls",
      "Baba Baidyanath Temple",
      "Ranchi Lake",
    ],
  },
  {
    state: "Karnataka",
    location: [
      "Bengaluru (Bangalore)",
      "Mysuru (Mysore)",
      "Coorg",
      "Hampi",
      "Badami",
      "Chikmagalur",
      "Gokarna",
      "Kabini",
      "Agumbe",
      "Sakleshpur",
      "Jog Falls",
      "Bijapur",
      "Murudeshwar",
      "Udupi",
      "Bhadra Wildlife Sanctuary",
    ],
  },
  {
    state: "Kerala",
    location: [
      "Kochi",
      "Thiruvananthapuram",
      "Alleppey (Alappuzha)",
      "Munnar",
      "Kumarakom",
      "Varkala",
      "Wayanad",
      "Thekkady",
      "Athirappilly",
      "Kollam",
      "Idukki",
      "Kovalam",
      "Bekal",
      "Meghamalai",
      "Silent Valley National Park",
    ],
  },
  {
    state: "Madhya Pradesh",
    location: [
      "Bhopal",
      "Indore",
      "Khajuraho",
      "Sanchi",
      "Gwalior",
      "Ujjain",
      "Orchha",
      "Kanha National Park",
      "Bandhavgarh National Park",
      "Pachmarhi",
      "Satpura National Park",
      "Mandu",
      "Chitrakoot",
      "Raisen Fort",
      "Rani Durgavati Fort",
    ],
  },
  {
    state: "Maharashtra",
    location: [
      "Mumbai",
      "Pune",
      "Aurangabad",
      "Nashik",
      "Lonavala",
      "Khandala",
      "Alibaug",
      "Mahabaleshwar",
      "Kolhapur",
      "Elephanta Caves",
      "Ajanta and Ellora Caves",
      "Ratnagiri",
      "Shirdi",
      "Matheran",
      "Tadoba National Park",
    ],
  },
  {
    state: "Manipur",
    location: [
      "Imphal",
      "Loktak Lake",
      "Kangla Fort",
      "Shree Shree Govindajee Temple",
      "Keibul Lamjao National Park",
      "Dzuko Valley",
      "Saheed Minar",
      "Ranganadi",
      "Bishnupur",
      "Manipur State Museum",
      "Sekmai",
      "Moirang",
      "Sangai National Park",
      "Tengnoupal",
      "Moirang",
    ],
  },
  {
    state: "Meghalaya",
    location: [
      "Shillong",
      "Cherrapunji",
      "Mawlynnong",
      "Nongriat",
      "Living Root Bridges",
      "Dawki",
      "Tura",
      "Pynursla",
      "Mawsmai Cave",
      "Umiam Lake",
      "Smit Village",
      "Balpakram National Park",
      "Jowai",
      "Laitmawsiang",
      "Elephant Falls",
    ],
  },
  {
    state: "Mizoram",
    location: [
      "Aizawl",
      "Lunglei",
      "Champhai",
      "Saitual",
      "Reiek",
      "Vantawng Falls",
      "Tiau River",
      "Durtlang Hills",
      "Phawngpui (Blue Mountain) National Park",
      "Murlen National Park",
      "Lengteng Wildlife Sanctuary",
      "Hmuifang",
      "Serchhip",
      "Bungtlang",
      "Zokhawthar",
    ],
  },
  {
    state: "Nagaland",
    location: [
      "Kohima",
      "Dimapur",
      "Wokha",
      "Mon",
      "Mokokchung",
      "Dzukou Valley",
      "Tuophema",
      "Japheth Village",
      "Zunheboto",
      "Kohima War Cemetery",
      "Kisama",
      "Shilloi Lake",
      "Intangki Wildlife Sanctuary",
      "Touphema Tourist Village",
      "Mount Japfu",
    ],
  },
  {
    state: "Odisha",
    location: [
      "Bhubaneswar",
      "Puri",
      "Konark",
      "Cuttack",
      "Chilika Lake",
      "Jagannath Temple",
      "Raghurajpur",
      "Bhitarkanika National Park",
      "Similipal National Park",
      "Dhauli",
      "Koraput",
      "Nandankanan Zoological Park",
      "Balaram Palace",
      "Barabati Fort",
      "Chandipur Beach",
    ],
  },
  {
    state: "Punjab",
    location: [
      "Amritsar",
      "Chandigarh",
      "Jalandhar",
      "Ludhiana",
      "Patiala",
      "Bhatinda",
      "Golden Temple (Harmandir Sahib)",
      "Wagah Border",
      "Anandpur Sahib",
      "Ropar (Rupar)",
      "Gobindgarh Fort",
      "Sukhna Lake",
      "Mata Vaishno Devi Mandir (Katra)",
      "Sheesh Mahal (Patiala)",
      "Harike Wetland and Bird Sanctuary",
    ],
  },
  {
    state: "Rajasthan",
    location: [
      "Jaipur",
      "Udaipur",
      "Jodhpur",
      "Jaisalmer",
      "Pushkar",
      "Bikaner",
      "Mount Abu",
      "Ajmer",
      "Chittorgarh",
      "Ranthambore National Park",
      "Kumbhalgarh Fort",
      "Alwar",
      "Sawai Madhopur",
      "Mandawa",
      "Tonk",
    ],
  },
  {
    state: "Sikkim",
    location: [
      "Gangtok",
      "Pelling",
      "Nathula Pass",
      "Tsomgo Lake",
      "Rumtek Monastery",
      "Yuksom",
      "Zuluk",
      "Ravangla",
      "Singalila National Park",
      "Khecheopalri Lake",
      "Bakthang Waterfall",
      "Changu Lake",
      "Khangchendzonga National Park",
      "Lachen",
      "Lachung",
    ],
  },
  {
    state: "Tamil Nadu",
    location: [
      "Chennai",
      "Madurai",
      "Coimbatore",
      "Ooty",
      "Kanyakumari",
      "Rameswaram",
      "Tiruchirappalli",
      "Kanchipuram",
      "Tirunelveli",
      "Thanjavur",
      "Mahabalipuram",
      "Coonoor",
      "Vellore",
      "Pondicherry",
      "Dindigul",
    ],
  },
  {
    state: "Telangana",
    location: [
      "Hyderabad",
      "Warangal",
      "Khammam",
      "Nizamabad",
      "Adilabad",
      "Srisailam",
      "Pochampally",
      "Bodhan",
      "Medak",
      "Ramappa Temple",
      "Nalgonda",
      "Jagityal",
      "Mahbubnagar",
      "Ramagundam",
      "Suryapet",
    ],
  },
  {
    state: "Tripura",
    location: [
      "Agartala",
      "Udaipur",
      "Unakoti",
      "Sepahijala Wildlife Sanctuary",
      "Neermahal",
      "Rudrasagar Lake",
      "Tripura Sundari Temple",
      "Jampui Hills",
      "Kailashahar",
      "Rajbari",
      "Matabari",
      "Dumboor Lake",
      "Lakshman Sagar",
      "Bagbasa",
      "Chabimura",
    ],
  },
  {
    state: "Uttar Pradesh",
    location: [
      "Agra",
      "Varanasi",
      "Lucknow",
      "Kanpur",
      "Mathura",
      "Ayodhya",
      "Aligarh",
      "Allahabad (Prayagraj)",
      "Vrindavan",
      "Jhansi",
      "Fatehpur Sikri",
      "Sarnath",
      "Bodh Gaya",
      "Dudhwa National Park",
      "Chitrakoot",
      "Noida",
    ],
  },
  {
    state: "Uttarakhand",
    location: [
      "Dehradun",
      "Nainital",
      "Mussoorie",
      "Rishikesh",
      "Haridwar",
      "Auli",
      "Jim Corbett National Park",
      "Kedarnath",
      "Badrinath",
      "Ranikhet",
      "Almora",
      "Tehri Lake",
      "Valley of Flowers",
      "Chopta",
      "Gangotri",
    ],
  },
  {
    state: "West Bengal",
    location: [
      "Kolkata",
      "Darjeeling",
      "Siliguri",
      "Sunderbans",
      "Murshidabad",
      "Shantiniketan",
      "Kalimpong",
      "Bishnupur",
      "Digha",
      "Dooars",
      "Bankura",
      "Santiniketan",
      "Cooch Behar",
      "Jalpaiguri",
      "Nadia",
    ],
  },
];

module.exports = indianStates;
